#!/usr/bin/env bash
# Installing Nginx web server that listens on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx start
