#!/usr/bin/env bash
# Installing Nginx web server that listens on port 80

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default
sudo service nginx reload
