#!/usr/bin/env bash
# Installing Nginx web server that listens on port 80

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# performing a 301 redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/amisoni70 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Creation of a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

sudo service nginx restart
