#!/usr/bin/env bash
# script that displays nos 1-20 with the case statement
i=0
while ((i<21))
do
	echo $i
	case "$i" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
		*) ;;
		esac
	((i++))
done
