#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 mins
Hours=0
while [ $Hours -lt 13 ]
do
	echo "Hour:$Hours"
	Mins=1
	while [ $Mins -lt 60 ]
	do
		echo "$Mins"
		((Mins++))
	done
	((Hours++))
done
