#!/usr/bin/env bash
# script that gives you information about a "School" file
FILE="school"
if [ -e "$FILE" ]
then
	echo "school file exists"
	if [ ! -s "$FILE" ]
	then
		echo "school file is empty"
	else [ -s "$FILE" ]
		echo "school file is not empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
